name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Build project
        run: |
          yarn install --immutable
          yarn check
          yarn build
        env:
          PUBLIC_DISCORD_INVITE: ${{ secrets.DISCORD_INVITE }}
